Many/Controllers/TransactionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Many.Data;
using Many.Models.MyModels;
using Many.Models;
using Microsoft.AspNetCore.Identity;
using Many.Models.MyViewModel;

namespace Many.Controllers
{
    public class TransactionsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public TransactionsController(ApplicationDbContext context,UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Transactions
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            ViewBag.Balance = user.Balance;
            var applicationDbContext = _context.TransactionsDb.Where(p=>p.IdReceived == user.Id || p.IdSent == user.Id).Include(t => t.ApplicationUserReceived).Include(t => t.ApplicationUserSent);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Transactions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var transactions = await _context.TransactionsDb
                .Include(t => t.ApplicationUserReceived)
                .Include(t => t.ApplicationUserSent)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (transactions == null)
            {
                return NotFound();
            }

            return View(transactions);
        }

        // GET: Transactions/Create
        public async Task<IActionResult> Create()
        {
            var user = await _userManager.GetUserAsync(User);
            ViewBag.Balance = user.Balance;
            ViewData["IdReceived"] = new SelectList(_context.Users, "Id", "Name");

            return View();
        }

        // POST: Transactions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateTranzactionsViewModel model, Transactions transactions)
        {
            var user = await _userManager.GetUserAsync(User);
            ViewBag.Balance = user.Balance;
            var user2 = await _context.Users.FirstOrDefaultAsync(r => r.UserName == model.Number);
            

            if (ModelState.IsValid && user.Balance>model.Money && user2!=null)
            {
                transactions.IdSent = user.Id;
                transactions.IdReceived = user2.Id;
                transactions.date = DateTime.Now;
                transactions.Money = model.Money;
                _context.Add(transactions);
                user.Balance -= model.Money;
                user2.Balance += model.Money;
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdReceived"] = new SelectList(_context.Users, "Id", "Name", transactions.IdReceived);

            return View(model);

        }
        public async Task<IActionResult> Replenish()
        {
            var user = await _userManager.GetUserAsync(User);
            ViewBag.Balance = user.Balance;


            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Replenish(CreateTranzactionsViewModel model, Transactions transactions)
        {
            var user = await _userManager.GetUserAsync(User);
            ViewBag.Balance = user.Balance;

            if (ModelState.IsValid)
            {
                transactions.IdSent = user.Id;
                transactions.IdReceived = user.Id;
                transactions.date = DateTime.Now;
                transactions.Money = model.Money;
                _context.Add(transactions);
                user.Balance += model.Money;
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }


            return View(model);

        }
        public async Task<IActionResult> AnonimReplenish()
        {

            ViewData["IdReceived"] = new SelectList(_context.Users, "Id", "Name");

            return View();
        }

        // POST: Transactions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AnonimReplenish(CreateTranzactionsViewModel model, Transactions transactions)
        {

            var user2 = await _context.Users.FirstOrDefaultAsync(r => r.UserName == model.Number);


            if (ModelState.IsValid && user2 != null)
            {
                transactions.IdSent = user2.Id;
                transactions.IdReceived = user2.Id;
                transactions.date = DateTime.Now;
                transactions.Money = model.Money;
                _context.Add(transactions);
                user2.Balance += model.Money;
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Home");
            }
            ViewData["IdReceived"] = new SelectList(_context.Users, "Id", "Name", transactions.IdReceived);

            return View(model);

        }
    }
}

Many/Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Many</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Many</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li><a asp-area="" asp-controller="Transactions" asp-action="Create">@Localizer["make_a_transaction"]</a></li>
                        <li><a asp-area="" asp-controller="Transactions" asp-action="Index">@Localizer["my_transactions"]</a></li>
                    }
                    @if (!SignInManager.IsSignedIn(User))
                    {
                        <li><a asp-area="" asp-controller="Transactions" asp-action="AnonimReplenish">@Localizer["replenish"]</a></li>
                    }
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Many</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>